issue #12 Footer Change(Light_Theme)
Harshita248/Scrum-Management pull request #57
Opened 2021-01-10 10:21 UTC by imsachinsingh10

in the issue #53 i forgot to update the Footer, so i made my changes in issue #12 , If it is not a problem then please accept it.
Regards Sachin,

I will be attaching Screen shots to show you how it works

2021-01-10 10:23 UTC, imsachinsingh10 commented
![Screenshot (72)](https://user-images.githubusercontent.com/46255113/104120323-ed1a8680-535b-11eb-9f57-d30359ce1ae9.png)

2021-01-10 12:38 UTC, Surajbokde requested changes

2021-01-10 12:38 UTC, Surajbokde commented on css/footer.css
> +  /* color: #e9e9e9; */
remove this comment

2021-01-12 10:19 UTC, merged

2021-01-21 17:33 UTC, imsachinsingh10 commented
Ma'am Please Label this pull request under SWoC because then only it will be considered as a successful PR under SWoC